[0m16:59:18.107305 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E5BD0D93A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E5BC454800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E5BF415D60>]}


============================== 16:59:18.122953 | 36fae1ba-cb55-4c06-99dd-7eca84f3b8fc ==============================
[0m16:59:18.122953 [info ] [MainThread]: Running with dbt=1.8.3
[0m16:59:18.122953 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Stagiaire\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m16:59:18.178127 [info ] [MainThread]: dbt version: 1.8.3
[0m16:59:18.178127 [info ] [MainThread]: python version: 3.12.4
[0m16:59:18.178127 [info ] [MainThread]: python path: C:\Users\Stagiaire\AppData\Local\Programs\Python\Python312\python.exe
[0m16:59:18.178127 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m16:59:18.262164 [info ] [MainThread]: Using profiles dir at C:\Users\Stagiaire\.dbt
[0m16:59:18.262164 [info ] [MainThread]: Using profiles.yml file at C:\Users\Stagiaire\.dbt\profiles.yml
[0m16:59:18.262164 [info ] [MainThread]: Using dbt_project.yml file at D:\dbt_workspace\DBT\dbt_project.yml
[0m16:59:18.262164 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m16:59:18.262164 [debug] [MainThread]: Command `dbt debug` failed at 16:59:18.262164 after 0.28 seconds
[0m16:59:18.262164 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E5BFC07B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E5BF80CCE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E5BF46BDA0>]}
[0m16:59:18.262164 [debug] [MainThread]: Flushing usage events
[0m17:02:39.111531 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002821A324560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002821A756060>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002821D0B68A0>]}


============================== 17:02:39.115543 | c0637947-c8b7-4aa6-b366-3fc9d07ab843 ==============================
[0m17:02:39.115543 [info ] [MainThread]: Running with dbt=1.8.3
[0m17:02:39.116522 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Stagiaire\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:02:39.134550 [info ] [MainThread]: dbt version: 1.8.3
[0m17:02:39.134550 [info ] [MainThread]: python version: 3.12.4
[0m17:02:39.138406 [info ] [MainThread]: python path: C:\Users\Stagiaire\AppData\Local\Programs\Python\Python312\python.exe
[0m17:02:39.139404 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m17:02:39.208358 [info ] [MainThread]: Using profiles dir at C:\Users\Stagiaire\.dbt
[0m17:02:39.208358 [info ] [MainThread]: Using profiles.yml file at C:\Users\Stagiaire\.dbt\profiles.yml
[0m17:02:39.208358 [info ] [MainThread]: Using dbt_project.yml file at D:\dbt_workspace\DBT\dbt_project.yml
[0m17:02:39.214934 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m17:02:39.215559 [debug] [MainThread]: Command `dbt debug` failed at 17:02:39.215559 after 0.23 seconds
[0m17:02:39.215559 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002821D596DB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002821D429F70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002821C91A6F0>]}
[0m17:02:39.215559 [debug] [MainThread]: Flushing usage events
[0m07:53:22.883534 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024783254110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000247821B21B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024782F80B30>]}


============================== 07:53:22.898308 | 84d48074-0600-4647-ac91-bb9f79eeda99 ==============================
[0m07:53:22.898308 [info ] [MainThread]: Running with dbt=1.8.3
[0m07:53:22.898847 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\Stagiaire\\.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run -models models_test', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m07:53:22.899873 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\dbt_workspace\DBT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m07:53:22.900844 [debug] [MainThread]: Command `dbt run` failed at 07:53:22.900844 after 0.14 seconds
[0m07:53:22.901868 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024782F08200>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000247821B21B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000247832541A0>]}
[0m07:53:22.901868 [debug] [MainThread]: Flushing usage events
[0m08:32:56.203799 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B6071E210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B60758690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B60759F90>]}


============================== 08:32:56.205796 | 9b392d2b-1dec-469d-b1e8-7a6cb405cbf8 ==============================
[0m08:32:56.205796 [info ] [MainThread]: Running with dbt=1.8.3
[0m08:32:56.207142 [debug] [MainThread]: running dbt with arguments {'use_experimental_parser': 'False', 'profiles_dir': 'C:\\Users\\Stagiaire\\.dbt', 'log_path': 'logs', 'invocation_command': 'dbt init', 'use_colors': 'True', 'introspect': 'True', 'printer_width': '80', 'target_path': 'None', 'debug': 'False', 'empty': 'None', 'log_cache_events': 'False', 'quiet': 'False', 'send_anonymous_usage_stats': 'True', 'write_json': 'True', 'indirect_selection': 'eager', 'cache_selected_only': 'False', 'warn_error': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'no_print': 'None', 'static_parser': 'True', 'fail_fast': 'False', 'version_check': 'True', 'partial_parse': 'True', 'log_format': 'default'}
[0m08:33:20.399664 [debug] [MainThread]: Starter project path: C:\Users\Stagiaire\Miniconda3\envs\dbt311\Lib\site-packages\dbt\include\starter_project
[0m08:33:20.436595 [info ] [MainThread]: 
Your new dbt project "dbt_bilbo_" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m08:33:20.438457 [info ] [MainThread]: Setting up your profile.
[0m08:34:08.150759 [info ] [MainThread]: Profile dbt_bilbo_ written to C:\Users\Stagiaire\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m08:34:08.153751 [debug] [MainThread]: Command `dbt init` succeeded at 08:34:08.153751 after 72.06 seconds
[0m08:34:08.154718 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B6073E2D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B5A304C10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020B5A304D50>]}
[0m08:34:08.155715 [debug] [MainThread]: Flushing usage events
[0m13:48:11.729672 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D6BE380D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D6BE3A190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D6BE3A7D0>]}


============================== 13:48:11.745301 | b50cf3b1-6358-4ae3-ab74-a4a64aab1543 ==============================
[0m13:48:11.745301 [info ] [MainThread]: Running with dbt=1.8.3
[0m13:48:11.745301 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\Stagiaire\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run -models models_test', 'send_anonymous_usage_stats': 'True'}
[0m13:48:11.745301 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\dbt_workspace\DBT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:48:11.757356 [debug] [MainThread]: Command `dbt run` failed at 13:48:11.756355 after 0.11 seconds
[0m13:48:11.757971 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D6BE329D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D6BE7E810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D6BE7E590>]}
[0m13:48:11.759001 [debug] [MainThread]: Flushing usage events
[0m13:48:35.152403 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221ECCA8FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221ECCA9B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221ECCAB350>]}


============================== 13:48:35.152403 | 5002e57c-154b-4c0f-9801-66dce4a6de05 ==============================
[0m13:48:35.152403 [info ] [MainThread]: Running with dbt=1.8.3
[0m13:48:35.152403 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Stagiaire\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run -models models_test', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:48:35.168028 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\dbt_workspace\DBT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:48:35.168028 [debug] [MainThread]: Command `dbt run` failed at 13:48:35.168028 after 0.10 seconds
[0m13:48:35.168028 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221ECCD2ED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221E65EA810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221EC06A410>]}
[0m13:48:35.168028 [debug] [MainThread]: Flushing usage events
[0m15:00:12.393440 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED1DB9B250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED1DB9B210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED1DB9B510>]}


============================== 15:00:12.393440 | 21bd5f54-dd1b-4563-abc1-80b4d3c25e1d ==============================
[0m15:00:12.393440 [info ] [MainThread]: Running with dbt=1.8.3
[0m15:00:12.393440 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Stagiaire\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run -recup_nom_columns', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:00:12.393440 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\dbt_workspace\DBT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:00:12.393440 [debug] [MainThread]: Command `dbt run` failed at 15:00:12.393440 after 0.10 seconds
[0m15:00:12.412437 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED1B254C50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED1DBD5C50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED1DA383D0>]}
[0m15:00:12.413240 [debug] [MainThread]: Flushing usage events
[0m15:00:58.190635 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028CF9F7B450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028CF99CC8D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028CF9F7A690>]}


============================== 15:00:58.190635 | 76857452-702b-4595-bbe6-c66e7107a0d4 ==============================
[0m15:00:58.190635 [info ] [MainThread]: Running with dbt=1.8.3
[0m15:00:58.190635 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Stagiaire\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt run -recup_nom_columns', 'send_anonymous_usage_stats': 'True'}
[0m15:00:58.190635 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\dbt_workspace\DBT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:00:58.206269 [debug] [MainThread]: Command `dbt run` failed at 15:00:58.206269 after 0.10 seconds
[0m15:00:58.213373 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028CF7640910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028CF9FB9E90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028CF9E18310>]}
[0m15:00:58.214312 [debug] [MainThread]: Flushing usage events
[0m15:01:16.658710 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296098F9B10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296098FAF90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296098FABD0>]}


============================== 15:01:16.658710 | 9101f8f5-06bc-4064-b980-3d2bc456e8d5 ==============================
[0m15:01:16.658710 [info ] [MainThread]: Running with dbt=1.8.3
[0m15:01:16.658710 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Stagiaire\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run -models recup_nom_columns', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:01:16.658710 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\dbt_workspace\DBT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:01:16.658710 [debug] [MainThread]: Command `dbt run` failed at 15:01:16.658710 after 0.10 seconds
[0m15:01:16.674359 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002960993DED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296098F2950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296098F8D50>]}
[0m15:01:16.674359 [debug] [MainThread]: Flushing usage events
[0m13:32:19.018672 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026DFB846D50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026DFBE39F10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026DFBE67390>]}


============================== 13:32:19.018672 | 600fef0e-a356-4c98-949c-fc11c5e78a54 ==============================
[0m13:32:19.018672 [info ] [MainThread]: Running with dbt=1.8.3
[0m13:32:19.018672 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Stagiaire\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run -models models_test', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:32:19.034317 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\dbt_workspace\DBT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:32:19.039990 [debug] [MainThread]: Command `dbt run` failed at 13:32:19.039459 after 0.11 seconds
[0m13:32:19.040781 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026DFBE32A10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026DFBE7DBD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026DFBE7E450>]}
[0m13:32:19.041792 [debug] [MainThread]: Flushing usage events
